name: ArXiv Discord Bot

on:
  push:
      branches:
        - main
  schedule:
    - cron: "0 7 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: "x64"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Running Script
        env:
          PROJECT1_WEBHOOK: ${{ secrets.PROJECT1_WEBHOOK }}
          PROJECT2_WEBHOOK: ${{ secrets.PROJECT2_WEBHOOK }}
        run: python bot.py

